name: Build and Deploy

on:
  push:
    branches:
      - main  # Adjust this as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Nix
        uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build site
        run: nix build .#defaultPackage.${{ matrix.system }} --print-build-logs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_PAGES_ACCESS }}
          publish_dir: ./output
